development:
  adapter: postgresql
  encoding: unicode
  database: vehiculum_dev
  pool: 5
  username: lukaszodziewa
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: vehiculum_test
  pool: 5
  username: lukaszodziewa
  password: 
